spring.application.name=backend
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:matchlens}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET:6FgTl+nlAU2SHMEtwy3H+dAPFkhJ55TSrglT/LLi8us=}
cors.allowed-origin=${CORS_ORIGIN:http://localhost:4200}
